### ISSUE TITLE
Handle user changing email in AuthRocket but not Microsetta

### ISSUE THREAD

**Issue by AmandaBirmingham** [biocore/microsetta-private-api#113]
Currently if a user changes their email in authrocket but not in microsetta, they will no longer be able to access their microsetta account even though their authrocket login is valid (will get a ValueError saying "Account email does not match authorization email").  Eventually we will need to support this use case.

**Comment by dhakim87** [comment]
Ugh.  I'm of the opinion that if their iss and sub field matches, we should really let them log in.  The sub field is the unique key assigned to users in authrocket (and oauth2), and won't change even if they federate 10 different email logins from various sources together.  The only time this doesn't fly is with claiming legacy accounts, where we don't know any information about the user except an email that they have had.  But after that process goes through, I don't see any reason to prevent access based on changing their email.  

Ideally whatever user interface component (minimalInterface for now...) would be able to hit some path to recognize that the email has changed, and ask the user if they would like to update their account email?  But we really shouldn't block access for this...

**Comment by AmandaBirmingham** [comment]
Functionality to recognize the email has changed and ask user if they would like to update their email account has been added in PR #119 .
