### ISSUE TITLE
Users are unsure of site sampled when collecting saliva

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#188]
The sample selection currently indicates Mouth. Changing this to saliva would impact all prior samples in Qiita, as would adding different entries types. An minor change could be adopted where below the site sampled pulldown, a small note is included "Note: if you took an oral or saliva sample, please choose "Mouth". "

**Comment by wasade** [comment]
On further discussion, we may actually want to differentiate this and allow specifically for someone to select "saliva". A mouth sample (e.g., a tongue) is different than the saliva collections we are now doing. Resolution of this issue would require modifying the API controlled vocabulary on sample assignment I think

**Comment by dhakim87** [comment]
Both this and #200 should wait for #202 to go in, since #202 swaps out the sample selection
