### ISSUE TITLE
Prevent survey submission when hitting enter in form

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#189]
A lot of participants are unsure whether the registration / consent / surveys are stored. Having a simple message noting this would help. The suggested text from Kat and Dom is "Thank you for submitting your consent form and questionnaires! We have received these and they are stored in the database."

What we'd really want to do is only show this the first time they arrive. That may require some state tracking which sucks. So not sure how best to do this...

**Comment by dhakim87** [comment]
If we're looking for a simpler change, we could also add another page to the workflow that tells them that they're done before redirecting them.  So after they finish the covid survey - "Thanks, you're all set!  Your blah blah blah has been all been received and stored.  Now we're taking you to your accounts page.  Redirecting in 5...4...3..."

**Comment by wasade** [comment]
Update: the decision is to disallow users to hit "enter" on the survey page. We'll resolve later how to notify the user a survey was definitely saved
