### ISSUE TITLE
API Navigation - Survey to Sample Associations

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-private-api#20]
Association of survey responses with samples is a little bit unclear: what triggers association or disassociation of surveys with samples?  Is this a form displayed to the end user?  If these associations are implicit based on timestamps, we can remove these routes from the yaml.

**Comment by wasade** [comment]
Right now, a user explicitly associates a sample to a participant and the relevant relationships are reflected in the database

**Comment by AmandaBirmingham** [comment]
@dhakim87  Does @wasade 's answer address your concern?  If so, please close this issue.  If not, please add more info on your question.  Thanks!

**Comment by dhakim87** [comment]
Replaced with integration testing issue #47 to make sure this is working as intended.
