### ISSUE TITLE
Confusion over selecting a blood sample

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#200]
There is confusion with selecting the sample type for the skin prick. Many are selecting a hand, which to be fair makes sense as they're pricking their finger. One thing we could do is add text along the lines of "If collecting a *BLOOD* sample, please select blood (skin prick)"

**Comment by dhakim87** [comment]
The calendar changes in #202 swap out this control.  We should fix this after 202 is merged in.
