### ISSUE TITLE
Require that each account have at least one source

### ISSUE THREAD

**Issue by AmandaBirmingham** [biocore/microsetta-private-api#209]
Per @wasade at https://github.com/biocore/microsetta-private-api/pull/170#discussion_r434864276 .  Need to decide how this should be implemented (since user has to be able to choose what source to add).

**Comment by wasade** [comment]
With the new administrator mode, I don't think it makes sense to require that every account have at least one source.

**Comment by wasade** [comment]
Closing as not needed
