### ISSUE TITLE
Determine and implement correct submission path for consent forms

### ISSUE THREAD

**Issue by AmandaBirmingham** [biocore/microsetta-private-api#27]
~~age_range IS used to decide which consent text to return--and we didn't implement that logic in the api yaml OR the python implementation~~

Consent endpoint returns a form, and embedded in that form is the age range question, when then determines what div fields of the consent text are shown--so we are good on employing consent to figure out what to show.  

What is unclear now is where the consent form results should be sent and how ... do we set the form's submit url to send results to the create source api endpoint but change that endpoint to expect non-json input (e.g., openapi3 supports the `multipart/form-data` media type)?  Or do we do ... something else?  Right now consent form submissions don't go anywhere meaningful, AFAIK, so *some* change is necessary.

**Comment by dhakim87** [comment]
Should be tested as part of the workflow to

Hook up the consent form from /consent to successfully create a new human source

Now part of milestone 1.

**Comment by wasade** [comment]
Good catch. In the present website, the consent information is carried along in a cache until the primary survey is completed. Only at the point of survey completion does the consent information stored in the DB. 

The new API does represent a divergence with the existing strategy. 

My initial guess is allowing a `POST` on `/consent` may be easiest, where that `POST` triggers an `INSERT` on the database for the corresponding details. The user would need to be authorized, (should this be `/authed/consent`?), and the `INSERT` at present requires that the system has sufficient context when the `POST` is received to determine the `ag_login_id`. This last constraint stems from how the `ag.ag_consent` table is currently defined, where it has a FK to `ag.ag_login`.
