### ISSUE TITLE
classmethod or staticmethod?

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#4]
[`AccountRepo._account_to_row`](https://github.com/biocore/microsetta-private-api/blob/52798b9823332114aa98b20a939cabdbbbdc1527/repo/account_repo.py#L21) and its inverse are currently decorated with `classmethod`, however these appear to instead be `staticmethod`s. Should these be changed?

**Comment by dhakim87** [comment]
Probably yes, as long as we don't need any specialized tailoring of json.

**Comment by wasade** [comment]
Neither of these are `classmethod`s per the typical use in Python as they do not return instances of a class or interact with a class definition. `classmethod`s are often used to provide multiple constructors for an object. 

Instead, the code here suggests the use of a `staticmethod`. Like a `classmethod`, it can be called on an uninitialized object. However, it cannot refer to the object itself -- these are often used to encapsulate logic that does not depend on instance state.

**Comment by wasade** [comment]
...basically, if you have:

```python
@classmethod
def foo(cls, bar):
        return bar + 5
```

...then there is no need for it to be a `classmethod` as it does not do anything with `cls`. 
...

**Comment by dhakim87** [comment]
Agree.  Static method is better in the current implementation.  Only time that might change is if the database requires specific json hooks or other configurable encoding for writing of fields to the database.  Honestly, it probably never will, so changing them to static method is good
