### ISSUE TITLE
Hook up consent form

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-private-api#44]
Hook up the consent form from /consent to successfully create a new human source.

**Comment by AmandaBirmingham** [comment]
@dhakim87  I think this is a duplicate of #27 ? Or am I missing something?

**Comment by dhakim87** [comment]
Yup!  Closing this one and assigning #27 to milestone 1.  
Duplicate of #27

**Comment by dhakim87** [comment]
Duplicate of #27

**Comment by wasade** [comment]
If this is a duplicate, should it be closed?
