### ISSUE TITLE
Bug with project association on campaign creation

### ISSUE THREAD

**Issue by cassidysymons** [biocore/microsetta-private-api#468]
When creating a campaign, this block of code in the create_campaign function is behaving inconsistently:

                cur.executemany(
                    "INSERT INTO campaign.campaigns_projects ("
                    "campaign_id,project_id"
                    ") VALUES (%s, %s) ",
                    [(campaign_id, pid) for pid in associated_projects]
                )

In some cases, it treats a single ID properly (e.g. 155 is inserted as 155), while in others, it treats each numeral in the ID as a different entry (e.g. 157 is inserted as three entries - 1, 5, and 7). Need to refactor this code to explicitly treat a comma as the only delimiter, rather than relying on default behavior.

**Comment by wasade** [comment]
Maybe add 

```python
if isinstance(associated_projects, str):
    associated_projects = [associated_projects, ]
```

immediately prior?
