### ISSUE TITLE
Assign A Survey To a Sample  

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-private-api#47]
Possible this only happens for the external surveys in the current implementation.  Currently exists in the api, should test that the implementaiton can handle it.

**Comment by AmandaBirmingham** [comment]
Unless I misunderstand, in the yaml api, samples are added to surveys rather than the other way around (via POST /accounts/{account_id}/sources/{source_id}/samples/{sample_id}/surveys ) .

**Comment by dhakim87** [comment]
"POST /accounts/{account_id}/sources/{source_id}/samples/{sample_id}/surveys"

Just looking at the url, it looks would create a survey and associate it with a sample.  

But as far as I can tell, survey to sample is supposed to be many to many, so I wouldn't really worry about what is assigned to what: 
3 samples associated with the same primary survey, the third sample is associated with an additional survey... seems to be a valid state?

**Comment by AmandaBirmingham** [comment]
> "POST /accounts/{account_id}/sources/{source_id}/samples/{sample_id}/surveys"
> Just looking at the url, it looks would create a survey and associate it with a sample.

Ah, but it DOESN'T!  That is to say, it doesn't create an (answered) survey--all it does is associate an existing answered survey to an existing sample.  If you want to create a new answered survey, you use the endpoint POST /accounts/{account_id}/sources/{source_id}/surveys (remember, survey is an object under both source AND sample endpoints ...)

You are correct that survey to sample is now envisioned as a many-to-many relationship, so you could certainly argue that it doesn't matter which we say is being assigned to which other ... but in the api, it is only possible to set up that association starting from the sample :)

**Comment by wasade** [comment]
I think it is beneficial to view it as samples being assigned to surveys rather than surveys being assigned to samples. It is possible to have a survey without associated collected samples, however our system does not allow for collected samples to exist without a survey.

**Comment by AmandaBirmingham** [comment]
>  It is possible to have a survey without associated collected samples, however our system does not allow for collected samples to exist without a survey.

Hmmm, @wasade do you want the api to enforce that?  Per the discussion in https://github.com/biocore/microsetta-private-api/issues/49#issuecomment-573236300 , right now the workflow the api supports is basically, attach an existing (but not yet "claimed") sample to a source, after which you can a) set the info for that sample (site, datetime collected, etc) and/or b) link that sample to an existing answered survey.  AFAIK there is nothing built into the api that *requires* you to do either a) or b), nor anything that requires you to do b) before a) (which is what I would think your comment implies ...)

**Comment by wasade** [comment]
Ah! I made a bad comment! Environmental samples are not associated with a
survey!
