### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#5]
It would be pleasant to have continuous integration setup to automatically trigger unit tests and other code base checks on pull requests

**Comment by kikilagou** [comment]
Hi, I came across this and run the project locally. I also tried making a simple .travis.yml file. Would something like this be what you are looking for (as a starting point)? just to let you know - I'm very new to open source

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
cache: pip
before_install:
  - export PYTHONPATH=$PYTHONPATH:/Users/kiklagou/Documents/open-source/microsetta-private-api-master/util/util.py
  - conda create -n microsetta-private-api flask psycopg2 natsort
  - conda activate microsetta-private-api
  - source activate microsetta-private-api
install:
  - "pip freeze > requirements.txt"
  - "pip install -r requirements.txt"
script:
  - "python -m unittest discover"

**Comment by wasade** [comment]
Hi @kikilagou, thank you for the inquiry and the curiosity about the project! 

That's a good first pass :) And also raises the point that we need to get our requirements in place, and should also get a `setup.py` -- I just created two issues to scope those. Note though that the CI `PYTHONPATH` probably should use relative paths :)

I realize this is not described at the moment, but the project is pure python 3. The tests will need to rely on a postrges database backend as well, so there is a little more trickery to the travis config to get that service setup. All that said, if you'd like to issue a pull request covering the items you've already outlined, it would certainly be welcomed!

**Comment by kikilagou** [comment]
Hi @wasade, thanks so much for this feedback :) I'll try improve what I have with the information you've given me and try to make a pull request (I'll try to mention changes here first). 
About the PYTHONPATH - sorry this was a bit rushed :) I wasn't 100% sure if it was even required in the travis file, I just couldn't run the server without setting this. 

Thanks again for the warm welcome
