### ISSUE TITLE
Handle language tag in survey questions, survey answers, and consent docs

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-private-api#50]
Decide on a minimal set of language_tags we will support for first milestone (probably en_us, en_gb), ensure that survey questions, survey answers, and consent documents properly handle the language_tag parameters.

**Comment by AmandaBirmingham** [comment]
Per @wasade : will do en-US and en-GB *only* for milestone 1.  Issue title has been changed to be about implementation of this.

**Comment by dhakim87** [comment]
Maybe check out https://github.com/LuminosoInsight/langcodes, it aims to properly normalize all the different formats for language tags and turn it into BCP 47, which for everything we'll do short term is equivalent to ISO 639-1.  Then we can just use their standard lookups in our code/database.

**Comment by dhakim87** [comment]
Done!
