### ISSUE TITLE
Unremoved interested users in `test_perk_fulfillment_repo.py`

### ISSUE THREAD

**Issue by colts661** [biocore/microsetta-private-api#556]
Interested users are created as a side effect of `add_transaction`:
https://github.com/biocore/microsetta-private-api/blob/464736e47235b8284267b9a2caa315141af665db/microsetta_private_api/repo/tests/test_perk_fulfillment_repo.py#L278

but deletion is not handled in `tearDown`, resulting in more interested users in the database every time the test file runs.

**Comment by cassidysymons** [comment]
@colts661 Good catch. Once https://github.com/biocore/microsetta-private-api/pull/555 is merged, can you please open a new PR to address this issue? Thanks!

**Comment by colts661** [comment]
Upon inspecting the code related to this issue, I find out that the `interested_user_id` created when creating the user is not returned from `add_transaction()`, so we're missing the unique identifier to remove the interested user from the testing situation, given that none of names, email, etc. can be used as the identifier.

**Comment by cassidysymons** [comment]
You can grab the `interested_user_id` from the `campaign.transaction` table based on the transaction's `id`. `UserTransaction.add_transaction()` always creates a new record in `campaign.interested_users` so it's safe to delete whatever is associated with those test transactions.
