### ISSUE TITLE
Drop Python 3.6?

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-private-api#65]
Do we have a reason to support python 3.6?  Some of the datetime formatting is cleaned up in 3.7 and may make our conversion code cleaner to make use of it.

**Comment by wasade** [comment]
:+1:

**Comment by dhakim87** [comment]
Argh, the python 3.7 datetime parser isn't all that much better.  They point us towards using a third party dateutil instead.  

>  classmethod datetime.fromisoformat(date_string)
> 
>     Return a datetime corresponding to a date_string in one of the formats emitted by date.isoformat() and datetime.isoformat().
> 
>     Specifically, this function supports strings in the format:
> 
>     YYYY-MM-DD[*HH[:MM[:SS[.fff[fff]]]][+HH:MM[:SS[.ffffff]]]]
> 
>     where * can match any single character.
> 
>     Caution
> 
>     This does not support parsing arbitrary ISO 8601 strings - it is only intended as the inverse operation of datetime.isoformat(). A more full-featured ISO 8601 parser, dateutil.parser.isoparse is available in the third-party package dateutil.
