### ISSUE TITLE
Change 403 error for not-found kit name to 404

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-private-api#74]
It would be nice to have a policy in place to determine which status codes are thrown when. See [here](https://github.com/biocore/microsetta-private-api/pull/61#issuecomment-589925466) and [here](https://github.com/biocore/microsetta-private-api/pull/61/files#r382179670) for existing discussion on this.

**Comment by AmandaBirmingham** [comment]
Per discussion w @wasade @dhakim87 : For https://github.com/biocore/microsetta-private-api/pull/61/files#r382179670 we will use 404 ... whatever it is you entered, we can't find it.  For other status codes that were in question, we will use 422.
