### ISSUE TITLE
Administrator Actions

### ISSUE THREAD

**Issue by dhakim87** [biocore/microsetta-private-api#97]
Create a framework for administrative actions.  

Administrators should be able to login through the portal and fix issues that customers encounter.

**Comment by dhakim87** [comment]
Primary items are: verify if a sample is associated with a person (see next note), change sample type, change sample date/time

on sample verification, there are 4 possibilities: the sample is assigned to someone, the sample is unassigned but the person who registered the kit consented and filled out a questionnaire, the sample is unassigned and the person who registered the kit has not completed consent or a questionnaire, or the fourth possibility is the sample is associated with an unregistered kit (edited) 
when the sample is unassigned, in the cases where its part of a registered kit, we need to be able to easily email the person (either getting their email address or the system sends them an email)

Administrators should be able to hit the same routes as clients which will necessitate changes in the permissions validation, and should be able to send templated emails for common requests for information/action from end users within the administrative portion of the system.

**Comment by wasade** [comment]
I believe this issue has been resolved
